version: '2'
services:
    frontend:
        build:
            dockerfile: DockerfileLocal
        volumes:
            - ./frontend:/app
            - frontend_node_modules:/app/node_modules/
    backend:
        build:
            dockerfile: DockerfileLocal
        volumes:
            - ./backend:/usr/src/app
    google_play:
        build:
            dockerfile: DockerfileLocal
        volumes:
            - ./google-play-service:/app
            - google_play_node_modules:/app/node_modules/

volumes:
    frontend_node_modules:
    google_play_node_modules:
