version: '3.5'

services:
    secrets:
        build:
            context: ./secrets
            dockerfile: Dockerfile
        volumes:
            - ./secrets/store:/root/store
    reverseproxy:
        build:
            context: ./reverseproxy
            dockerfile: Dockerfile
        depends_on:
            - vue
            - flask
            - embedding
        ports:
            - 443:8081
            - 80:8080
        volumes:
            - ./reverseproxy/ssl:/etc/nginx/conf.d/ssl
    vue:
        build:
            context: ./frontend-demo
            dockerfile: Dockerfile
    flask:
        build:
            context: ./backend-demo
            dockerfile: Dockerfile
        volumes:
            - ./backend-demo:/usr/src/app
            - ./backend-demo/models:/usr/src/app/models
        depends_on:
            - secrets
            - postgres
        secrets:
            - jwt_key
    colibert:
        build:
            context: ./colibert-service
            dockerfile: Dockerfile
        volumes:
            - transformers:/root/.cache/transformers/
    postgres:
        build:
            context: ./postgres
            dockerfile: Dockerfile
        shm_size: 1g
        command: postgres -c 'max_connections=1000'
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: omp
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
    embedding:
        build:
            context: ./embedding-service
            dockerfile: Dockerfile
        volumes:
            - ./embedding-service:/app
            - ./embedding-service/model:/app/model
        depends_on:
            - postgres

volumes:
    postgres:
    transformers:

secrets:
    jwt_key:
        file: ./secrets/store/jwt_key
