version: '2'
services:
    reverseproxy:
        build: 
            dockerfile: DockerfileLocal
    vue:
        build: 
            dockerfile: DockerfileLocal
        volumes:
            - ./frontend-demo:/app
    flask:
        mem_limit: 10G