version: '2'
services:

    reverseproxy:
        build: 
            context: ./reverseproxy
            dockerfile: Dockerfile
        ports:
            - 443:8081
            - 80:8080
        restart: always

    vue:
        build: 
            context: ./frontend-demo
            dockerfile: Dockerfile
        depends_on:
            - reverseproxy
    flask:
        build:
            context: ./backend-demo
            dockerfile: Dockerfile
        volumes:
            - ./backend-demo:/usr/src/app
        depends_on:
            - reverseproxy
        links:      
           - mongo
    meta:
        build:
            context: ./metacomment-service
            dockerfile: Dockerfile
        volumes:
            - ./metacomment-service:/app
        depends_on:
            - reverseproxy
        links:      
           - mongo
    mongo:
        image: mongo
        volumes:
            - mongodb:/data/db
        ports:
            - 27017:27017
#    offlang:
#        build:
#            context: ./offlang-service
#            dockerfile: Dockerfile
#        volumes:
#            - ./offlang-service:/app
#        depends_on:
#            - reverseproxy
#        links:
#            - mongo
    embedding:
        build:
            context: ./embedding-service
            dockerfile: Dockerfile
        volumes:
            - ./embedding-service:/app
            - ./embedding-service/model:/app/model
        depends_on:
            - reverseproxy
        links:
            - mongo
volumes:
    mongodb:
