version: '3.5'

services:
    secrets:
        build:
            context: ./secrets
            dockerfile: Dockerfile
        volumes:
            - ./secrets/store:/root/store
    reverseproxy:
        build:
            context: ./reverseproxy
            dockerfile: Dockerfile
        depends_on:
            - frontend
            - backend
            - embedding
        ports:
            - 443:8081
            - 80:8080
        volumes:
            - ./reverseproxy/ssl:/etc/nginx/conf.d/ssl
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - backend_models:/usr/src/app/models
        depends_on:
            - secrets
            - db
        secrets:
            - jwt_key
            - db_password
    colibert:
        build:
            context: ./colibert-service
            dockerfile: Dockerfile
        volumes:
            - transformers:/root/.cache/transformers/
    db:
        build:
            context: ./database
            dockerfile: Dockerfile
        shm_size: 1g
        command: postgres -c 'max_connections=1000'
        volumes:
            - db_data:/var/lib/postgresql/data
        depends_on:
            - secrets
        environment:
            POSTGRES_DB: forum40
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
        secrets:
            - db_password
        ports:
            - 5432:5432
    embedding:
        build:
            context: ./embedding-service
            dockerfile: Dockerfile
        environment:
            API_ROOT_PATH: /api/embedding
        volumes:
            - sentence_transformers:/root/sentence-transformers/

volumes:
    db_data:
    transformers:
    sentence_transformers:
    backend_models:

secrets:
    jwt_key:
        file: ./secrets/store/jwt_key
    db_password:
        file: ./secrets/store/db_password.txt
