version: '2'
services:
    vue:
        build:
            dockerfile: DockerfileLocal
        volumes:
            - ./frontend-demo:/app
            - vue_node_modules:/app/node_modules/
    flask:
        mem_limit: 10G

volumes:
    vue_node_modules:
