version: '2'
services:
    frontend:
        build:
            dockerfile: DockerfileLocal
        volumes:
            - ./frontend:/app
            - frontend_node_modules:/app/node_modules/
    backend:
        build:
            dockerfile: DockerfileLocal
        volumes:
            - ./backend:/usr/src/app

volumes:
    frontend_node_modules:
