version: '2'
services:
    frontend:
        build:
            dockerfile: DockerfileLocal
        volumes:
            - ./frontend:/app
            - frontend_node_modules:/app/node_modules/
    backend:
        mem_limit: 10G

volumes:
    frontend_node_modules:
